consumes:
- application/com.github.ASVBPREAUBV.go-test.v1+json
info:
  description: Test Swagger for go App
  title: A Test application
  version: 0.0.1
paths: {}
produces:
- application/io.goswagger.examples.todo-list.v1+json
schemes:
- http
swagger: "2.0"
definitions:
  item:
    type: object
    required:
    - description
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      description:
        type: string
        minLength: 1
      completed:
        type: boolean